// constants/departments.js
export const DEPARTMENTS = [
  "Leadership",
  "Development",
  "Marketing & Design",
  "Mechanical Team",
  "HR",
  "Management",
];

export const DESIGNATIONS = [
  "Founder & CEO",
  "Co-Founder",
  "HR Manager",
  "HR Executive",
  "Senior Developer",
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "UI/UX Designer",
  "Graphic Designer",
  "Digital Marketing Manager",
  "SEO Specialist",
  "Social Media Manager",
  "Content Writer",
  "Mechanical Engineer",
   "AI & Python",
  "CAD Designer",
  "Project Manager",
  "Intern",
  "Team Lead",
  "Other",
];

export const SKILLS = [
  "React.js",
  "Next.js",
  "Node.js",
  "Python",
  "Java",
  "JavaScript",
  "TypeScript",
  "HTML/CSS",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "AWS",
  "Docker",
  "Git",
  "UI/UX Design",
  "Figma",
  "Adobe XD",
  "Photoshop",
  "Illustrator",
  "SEO",
  "Digital Marketing",
  "Content Writing",
  "AutoCAD",
  "SolidWorks",
  "CATIA",
  "Pro-E",
  "Revit",
  "STAAD Pro",
];